zstyle ':completion:*' use-cache yes
zstyle ':completion:*' cache-path ~/.zsh/cache
compinit -C

# AGKOZAK_MULTILINE=0
# AGKOZAK_PROMPT_CHAR=( ❯ ❯ "%F{red}N%f")
autoload -Uz history-search-end

zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end

hash go 2>/dev/null && export PATH=$PATH:$(go env GOPATH)/bin
hash yarn 2>/dev/null && export PATH=$PATH:$HOME/.yarn/bin
hash dotnet 2>/dev/null && export PATH=$PATH:$HOME/.dotnet/tools

# Rancher Manager path
export PATH=$PATH:$HOME/.rd/bin
export PATH=$PATH:$HOME/.local/bin

_direnv_hook() {
    trap -- '' SIGINT
    eval "$("direnv" export zsh)"
    compinit 2> /dev/null
    trap - SIGINT
}
typeset -ag precmd_functions
if (( ! ${precmd_functions[(I)_direnv_hook]} )); then
    precmd_functions=(_direnv_hook $precmd_functions)
fi
typeset -ag chpwd_functions
if (( ! ${chpwd_functions[(I)_direnv_hook]} )); then
    chpwd_functions=(_direnv_hook $chpwd_functions)
fi


eval "$(/opt/homebrew/bin/brew shellenv)"
